wso2/identity-test-integration

- commons/src/main/java/org/wso2/qa/commons/operations/LoginOperations.java
- commons/src/main/java/org/wso2/qa/commons/pageobjects/login/LoginPage.java
- commons/src/main/java/org/wso2/qa/commons/pageobjects/menus/MenuItems.java
- commons/src/main/java/org/wso2/qa/commons/pageobjects/serviceprovider/ServiceProviderConfigurePage.java
- commons/src/main/java/org/wso2/qa/commons/pageobjects/serviceprovider/ServiceProviderCreatePage.java
- commons/src/main/java/org/wso2/qa/commons/pageobjects/serviceprovider/ServiceProviderListPage.java
- commons/src/main/java/org/wso2/qa/commons/testbase/TestBase.java
- commons/src/main/java/org/wso2/qa/commons/util/ElementLocatorProperties.java
- commons/src/main/java/org/wso2/qa/commons/util/TestSuiteProperties.java
- commons/src/main/resources/locator.properties
- commons/src/main/resources/test-suite.properties
- solution18/src/test/java/org/wso2/qa/solution18/LoginTest.java
> resolving test issues.

- solution05/pom.xml
- solution05/src/test/jmeter/Solution-05.jmx
Adding Solution05 Configurations without tests.
> Adding Solution05

- README.md
- solution12/pom.xml
- solution12/src/test/jmeter/ClaimMapperScenario12.jmx
> Adding Solution12

- solution10/src/test/jmeter/SAML2_Bearer_Assertion_Profile_of_OAuth_2.0_with_WSO2_Travelocity.jmx
This fix the sp name which didn't have tomcat travelocity deployment prefix.
> Fixes for the SP name

- solution12/src/test/jmeter/ClaimMapperScenario12.jmx
Claim Mapper with travelocity service provider and idp facebook
> updated solution 12

- README.md
- pom.xml
- solution14/pom.xml
- solution14/src/test/jmeter/solution14.jmx
> Initial commit of scenario 14

- solution23/src/test/jmeter/solution23.jmx
> Updating server host details

- solution05/src/test/jmeter/Solution-05.jmx
Following will be added,
- Integrate the testing flow for Basic and redirect to Facebook
> Solution 05  - MFA for Management Console

- pom.xml
- solution21/pom.xml
- solution21/src/test/jmeter/FBfedarated.jmx
> Solution21 Commit

- solution05/pom.xml
- solution05/src/test/jmeter/MFA.jmx
- solution05/src/test/jmeter/ResourceCleaning.jmx
- Add a script to delete IDP
- Update local pom.xml
> AddAScriptForDeleteIDP

- README.md
- solution14/src/test/jmeter/solution14.jmx
Corrected the solution order in README.md
Cleaned the scenario 14 script by removing listeners and renaming samplers
> Corrected order in README.md and cleaned the scenario 14 script by removing listeners and renaming samplers

- .gitignore
- README.md
- solution29/pom.xml
- solution29/src/test/jmeter/Service provider-specific user stores.jmx
> add solution 29

- solution12/src/test/jmeter/ClaimMapperScenario12.jmx
Added Google IDP with OAUTH Fedarated Authenticator for Claim Mapping
> Claim Mapper Updated

- solution22/pom.xml
- solution22/src/test/jmeter/00-Create-Test-Users.jmx
- solution22/src/test/jmeter/01-Create-IDP.jmx
- solution22/src/test/jmeter/02-Create-SP.jmx
- solution22/src/test/jmeter/04-Delete-SP.jmx
- solution22/src/test/jmeter/05-Delete-IDP.jmx
- solution22/src/test/jmeter/09-Remove-Test-Users.jmx
- solution22/src/test/resources/user.properties
Updating with property files and proper order
> Updating with property files and proper order

- solution14/src/test/jmeter/solution14.jmx
Improved the assertions and mapped the claim to a appropriate attribute
> Improved the assertions

- solution14/src/test/jmeter/solution14.jmx
Added a negative scenario the script
> Added negative scenario to the script

- solution28/src/test/jmeter/HomeRelamNegative.jmx
Home Relam negative scenario - when the fidp is not defined
> Home Relam Negative Scenario

- solution29/src/test/jmeter/service_provider_specific_user_ stores.jmx
JMeter version is changed to 3.2 and re-generated the script.
> change the jmeter version to 3.2 and created the script

- solution02/src/test/jmeter/Soulution-02.jmx
Home Relam negative scenario - when the fidp is not defined
> Fix the issue in SP deletion

- pom.xml
- solution17/pom.xml
- solution17/src/test/jmeter/SecureSPA_OauthSecuredProxy.jmx
This includes solution 17 jmeter script.
> Commit Solution 17

- solution05/src/test/jmeter/MFA.jmx
- solution05/src/test/jmeter/ResourceCleaning.jmx
Include a negative scenario where Multi Factor Authenticator process fails with invalid credentials for Basic authenticator in 1st step.
> Adding Negative Scenarios

- solution22/pom.xml
- solution22/src/test/jmeter/02-Create-SP.jmx
- solution22/src/test/jmeter/03-SAML2_get_JWT_Token.jmx
- solution22/src/test/jmeter/04-Delete-SP.jmx
- solution22/src/test/resources/user.properties
updated solution22 with assertions plus missing checks.
> updated solution22 with assertions

- solution22/src/test/jmeter/02-Create-SP.jmx
- solution22/src/test/jmeter/03-SAML2_get_JWT_Token.jmx
- solution22/src/test/resources/user.properties
fixing oauth2 app and travelocity assertion
> fixing oauth2 app and travelocity assertion

- README.md
- pom.xml
- solution15/pom.xml
- solution15/src/test/jmeter/Federation_Proxy.jmx
Solution 15.0 Federation Proxy scenario added to the repo.
> Solution 15.0 Federation Proxy

- README.md
- pom.xml
- solution06/pom.xml
- solution06/src/test/jmeter/01Scenario6ConfiguringTest.jmx
- solution06/src/test/jmeter/02ResourceCleaningScenario6.jmx
Initial commit of solution 6. This contains the needed SP and IDP configuration script as well as a cleanup script for SP and IDP.
> Initial commit of solution 6

- pom.xml
- solution25/README.md
- solution25/pom.xml
- solution25/src/test/jmeter/Fine_grained_access_control_for_SOAP_services .jmx
This includes JMeter script of automating solution 25
> Adding solution 25

- solution11/pom.xml
- solution11/src/test/jmeter/Incompatible_identity_federation_protocols.jmx
- solution11/src/test/resources/user.properties
- solution29/pom.xml
- solution29/src/test/jmeter/service_provider_specific_user_ stores.jmx
- solution29/src/test/resources/user.properties
Solution29 - parameterized
Solution11 - parameterized
> parameterized solution29 and solution11

- solution12/README.md
- solution12/pom.xml
- solution12/src/test/jmeter/ClaimMapperScenario12.jmx
- solution12/src/test/resources/user.properties
> Parameterizing variables

- solution12/src/test/jmeter/ClaimMapperScenario12.jmx
- solution12/src/test/resources/user.properties
> changed travelocity properties

- solution05/src/test/jmeter/MFA.jmx
- solution05/src/test/jmeter/ResourceCleaning.jmx
- solution05/src/test/resources/user.properties
Parameters were modified for 2 scripts.
> Modiy Parameterizing 

- solution12/src/test/resources/user.properties
> added changes

- solution12/src/test/jmeter/ClaimMapperScenario12.jmx
- solution12/src/test/resources/user.properties
> adding chagnes

- solution11/src/test/jmeter/Incompatible_identity_federation_protocols.jmx
- solution11/src/test/resources/user.properties
- solution29/src/test/jmeter/service_provider_specific_user_ stores.jmx
- solution29/src/test/resources/user.properties
host changed to server_host. 
port changed to server_port
> Changed parameters accordingly in Solution29 and Solution11

- solution14/src/test/jmeter/solution14.jmx
- solution14/src/test/resources/user.properties
1. Corrected the property file conventions.
2. Removed a commented section in negative scenario
> corrected the property file convention

- solution21/pom.xml
- solution21/src/test/jmeter/FBfedarated.jmx
- solution21/src/test/resources/user.properties
* Altering the Jmeter file
* Altering the user.property file
* Remove the dependency with solution 22
> Committing the soultion 21 once altering required files

- solution17/src/test/jmeter/SecureSPA_OauthSecuredProxy.jmx
- solution17/src/test/resources/user.properties
- solution25/src/test/jmeter/Fine_grained_access_control_for_SOAP_services .jmx
- solution25/src/test/resources/user.properties
Modified call back urls in jmeter scripts and user.properties files
> Modify user.properties files of solution 17 and 25

- solution18/src/test/teardown.sh
> added bash.

- solution23/src/test/jmeter/solution23.jmx
- solution23/src/test/resources/user.properties
> Modified property names

- solution02/src/test/base-setup.sh
- solution02/src/test/jmeter/02-post-scenario-steps.sh
- solution02/src/test/jmeter/02-pre-scenario-steps.sh
- solution02/src/test/teardown.sh
- solution10/src/test/base-setup.sh
- solution10/src/test/jmeter/10-post-scenario-steps.sh
- solution10/src/test/jmeter/10-pre-scenario-steps.sh
- solution10/src/test/teardown.sh
- solution12/src/test/base-setup.sh
- solution12/src/test/jmeter/12-post-scenario-steps.sh
- solution12/src/test/jmeter/12-pre-scenario-steps.sh
- solution12/src/test/teardown.sh
- solution21/src/test/base-setup.sh
- solution21/src/test/jmeter/21-post-scenario-steps.sh
- solution21/src/test/jmeter/21-pre-scenario-steps.sh
- solution21/src/test/teardown.sh
- solution22/src/test/jmeter/22-post-scenario-steps.sh
- solution22/src/test/jmeter/22-pre-scenario-steps.sh
- solution22/src/test/teardown.sh
- solution25/src/test/base-setup.sh
- solution25/src/test/jmeter/25-post-scenario-steps.sh
- solution25/src/test/jmeter/25-pre-scenario-steps.sh
- solution25/src/test/teardown.sh
- solution28/src/test/base-setup.sh
- solution28/src/test/jmeter/28-post-scenario-steps.sh
- solution28/src/test/jmeter/28-pre-scenario-steps.sh
- solution28/src/test/teardown.sh
> updated scenario scripts with wso2 copyrights

- solution02/src/test/base-setup.sh
- solution12/src/test/base-setup.sh
- solution18/src/test/base-setup.sh
- solution21/src/test/base-setup.sh
- solution22/src/test/base-setup.sh
- solution28/src/test/base-setup.sh
SAML2.IdPEntityId should be configured in travelocity.properties files hence updated the scripts as applicable.
> updated scripts by adding SAML2.IdPEntityId param

- solution11/src/test/jmeter/Incompatible_identity_federation_protocols.jmx
- solution11/src/test/resources/user.properties
- solution29/src/test/jmeter/service_provider_specific_user_ stores.jmx
- solution29/src/test/resources/user.properties
Solution 11 and Solution 29 - Changed variable names to camelCase.
> change variable names to camelCase

- solution18/src/test/base-setup.sh
- solution18/src/test/jmeter/18-pre-scenario-steps.sh
- solution22/src/test/jmeter/00-Create-Test-Users.jmx
- solution22/src/test/jmeter/01-Create-IDP.jmx
- solution22/src/test/jmeter/02-Create-SP.jmx
- solution22/src/test/jmeter/03-SAML2_get_JWT_Token.jmx
- solution22/src/test/jmeter/04-Delete-SP.jmx
- solution22/src/test/jmeter/05-Delete-IDP.jmx
- solution22/src/test/jmeter/09-Remove-Test-Users.jmx
Updated deployment scripts to build the Travelocity application from the source.
> updated deployment scripts to build travelocity app from source

- solution02/src/test/jmeter/01-Soulution-02-Facebook.jmx
- solution02/src/test/jmeter/02-Soulution-02-Google.jmx
- solution02/src/test/resources/user.properties
> Fixing issues in script 

- solution23/pom.xml
- solution23/src/test/jmeter/solution23.jmx
Updated jmeter script and pom file for below changes:
Fix on jmx file.
Adding filename to pom.xml file
> Updated jmeter script and pom file

- solution23/README.md
- solution23/src/test/base-setup.sh
- solution23/src/test/jmeter/23-post-scenario-steps.sh
- solution23/src/test/jmeter/23-pre-scenario-steps.sh
- solution23/src/test/jmeter/solution23.jmx
- solution23/src/test/jmeter/solution23_B.jmx
- solution23/src/test/teardown.sh
Adding bash script to make auto run possibly:
solution23/src/test/base-setup.sh
solution23/src/test/teardown.sh
solution23/src/test/jmeter/23-post-scenario-steps.sh
solution23/src/test/jmeter/23-pre-scenario-steps.sh
Fix done for jmeter script: Fixed the issue with ACS url updating dinamically
> Adding bash script for auto run, and fixed jmeter script

- solution02/src/test/base-setup.sh
Added condition to check if the application gets deployed on tomcat.
> Added improvements to handle app deployment on tomcat

- solution02/src/test/jmeter/02-Soulution-02-Google.jmx
> Parameterized variables 

- solution27/src/test/jmeter/Solution-27-AttributeStoreValidations.jmx
- solution27/src/test/resources/user-creation.csv
Add support to read values from csv
> Add support to read values from csv

- solution14/README.md
- solution14/src/test/jmeter/solution14.jmx
> Added readme to the solution and another test to the solution
> Add readme and a test to verify login with new password

- solution02/pom.xml
- solution02/src/test/jmeter/01-Soulution-02-Facebook.jmx
- solution02/src/test/jmeter/03-Soulution-02-ISasIDP.jmx
- solution02/src/test/jmeter/04-Soulution-02-EmailOTP.jmx
- solution02/src/test/resources/user.properties
> 
- Fix issues in IS as IDP script
- New script for Email OTP
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
> Email OTP 

- solution01/README.md
- solution01/pom.xml
- solution01/src/test/jmeter/Solution1.jmx
- solution01/src/test/resources/user.properties
> Scenario 1.0 - Single Sign On between multiple heterogeneous identity federation protocols of [1]
[1] https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389
> Adding Solution 01

- scenario-metadata.yml
>Fixing the issue #147  - Metadata file to map scenarios
> Metadata file to map scenarios

- README.md
> To update the readme file with latest changes done to 'identity-test-integration' repo.
> Update the word 'Solution' to 'Scenario'
> Added missing scenarios in Read Me
> Update ReadMe with latest Changes

- scenario06/jmeter/01-Soulution-02-ProvisionFederatedUserstotenant.jmx
- scenario06/jmeter/01Scenario6ConfiguringTest.jmx
> Solution 6- Script for  Provision federated users to a tenant
> Adding script for  Provision federated users to a tenant

- scenario12/base-setup.sh
- scenario21/base-setup.sh
> Fixing the relative paths in the base-setup script to match the directory structure
> Modify relative paths in the base-setup script

- scenario18/base-setup.sh
- scenario18/jmeter/18-pre-scenario-steps.sh
- scenario18/jmeter/Fine-grained-acces-controlforSP.jmx
- scenario18/teardown.sh
> Change the scripts to run Scenario 18 to run in TG.
> Solve config issues
> Folowed the Tool kit and did some changes needed
> Solution 18 in https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389
> N/A
> https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389
> N/A
> N/A
> N/A
- Unit tests 
> Automation script
- Integration tests
> N/A
- yes
- yes
- yes
>As mentioned in the blog
> N/A
>N/A
> JDK 8, Tomcat 7.0.39, jmeter 3.2
> Jmeter knowledge
> Committing the updated scripts to run scenario 18 in TG

- scenario23/base-setup.sh
- scenario23/jmeter/04-Scenario-23-OAuthBearerRequestPathAuthenticator-RegisterOAuthApp.jmx
- scenario23/jmeter/05-Scenario-23-OAuthBearerRequestPathAuthenticator-Login.jmx
- scenario23/jmeter/06-Scenario-23-OAuthBearerRequestPathAuthenticator-Negative1.jmx
- scenario23/jmeter/07-Scenario-23-OAuthBearerRequestPathAuthenticator-Negative2.jmx
- scenario23/jmeter/10-Scenario-23-RemoveSps.jmx
- scenario23/jmeter/23-pre-scenario-steps.sh
- scenario23/resources/user.properties
- scenario23/teardown.sh
- Parameterize the properties in the jmeter scripts to read values from the user.properties file
- Modify the hardcoded values and incorporate directory structure changes
> Modify the scripts of scenario 23

- scenario18/jmeter/01-Scenario-18-Fine-grained-acces-controlforSP.jmx
> Changes done to the solution 18 after review
> committing changes done after review

- apps/playground2/pom.xml
>Changed the playground app pom.xml
> changed the playground app pom.xml

- scenario14/base-setup.sh
- scenario14/jmeter/01-Scenario14-EnforcePasswordReset.jmx
- scenario14/jmeter/14-post-scenario-steps.sh
- scenario14/jmeter/14-pre-scenario-steps.sh
> Modify the scripts to comply with TG for scenario 14
> Modify the scripts to comply with TG - scenario 14

- scenario02/jmeter/01-Soulution-02-Facebook.jmx
- scenario02/jmeter/02-Soulution-02-Google.jmx
- scenario02/resources/user.properties
>Adding Hostname of the extnal IS
> Adding Hostname of the extnal IS

- scenario14/README.md
- scenario14/jmeter/01-Scenario14-EnforcePasswordReset.jmx
> Add readme and improve the script.
> Add readme and improve the script

- scenario28/jmeter/01-Scenario-28-HomeRelam.jmx
> Remove the unused samplers and threads
> Remove unused sampler and threads

- scenario12/jmeter/01-Solution-12-ClaimMapper.jmx
Add logout request and modify the script
> Add logout request and modify

- scenario01/resources/user.properties
> corrected the username of admin in user.properties
> committing changes done to scenario 01

- scenario21/base-setup.sh
- scenario21/jmeter/01-Scenario-21-EnforceUsersToProvideMissingRequiredAttributesWhileGettingJITProvisioned.jmx
- scenario21/jmeter/21-pre-scenario-steps.sh
- scenario21/resources/user.properties
- scenario21/teardown.sh
> Update the scripts and user properties
> Update the scripts and user properties of scenario 21

- scenario06/base-setup.sh
- scenario06/jmeter/01-Scenario-06-ConfiguringTest.jmx
- scenario06/jmeter/02-Scenario-06-ProvisionFederatedUserstotenant.jmx
- scenario06/jmeter/03-Scenario-06-ResourceCleaning.jmx
- scenario06/jmeter/06-post-scenario-steps.sh
- scenario06/jmeter/06-pre-scenario-steps.sh
- scenario06/teardown.sh
> Add pre-post scripts for scenario 06
> Add pre-post scripts for scenario 06

- scenario02/jmeter/01-Scenario-02-Facebook.jmx
- scenario02/jmeter/02-Scenario-02-Google.jmx
- scenario02/jmeter/03-Scenario-02-ISasIDP.jmx
- scenario02/jmeter/04-Scenario-02-EmailOTP.jmx
- scenario02/resources/user.properties
> Update the scripts with changes to federated authenticators
> Update the scripts with changes to federated authenticators

- scenario10/base-setup.sh
- scenario10/jmeter/10-pre-scenario-steps.sh
- scenario10/jmeter/Scenario10_SAML2_Bearer_Assertion_Profile_of_OAuth_2.0_with_WSO2_Travelocity.jmx
- scenario10/resources/user.properties
> PR contains Positive and Negative tests to validate scenario 10 (Single Sign-On with delegated access control).
> Scripts should be Testgrid compatible.
> Scenario 10 Positive and Negative tests

- WSO2Scenariofile.yml
> Added WSO2Scenariofile.yml to defined configs related to scenarios.
>  Added WSO2Scenariofile.yml to defined configs related to scenarios.

- scenario01/README.md
- scenario01/jmeter/01-Scenario-1-SSO-multiple-heterogeneous-IDFP.jmx
- scenario01/resources/user.properties
> Adding Improvements to Scenario 01 according to the review.
> Adding Improvements to Scenario 01

- scenario18/jmeter/01-Scenario-18-Fine-grained-acces-controlforSP.jmx
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
> committing updated script with an issue fix

- scenario12/jmeter/01-Solution-12-ClaimMapper.jmx
> Add sol12 modifications

- scenario28/base-setup.sh
- scenario28/jmeter/01-Scenario-28-HomeRelam.jmx
> Disable ResponseSigning, AssertionSigning, RequestSigning in Travelocity app. Include the missing 'FBIdentityProviderName' user defined variable.
> Disable signing in Travelocity app

- scenario14/jmeter/01-Scenario14-EnforcePasswordReset.jmx
> Edit sampler names for clarity
> Edit sampler names for clarity

- scenario22/base-setup.sh
- scenario22/jmeter/01-Scenario-22-Create-Test-Users.jmx
- scenario22/jmeter/02-Scenario-22-Create-IDP.jmx
- scenario22/jmeter/03-Scenario-22-Create-SP.jmx
- scenario22/jmeter/04-Scenario-22-SAML2-Get-JWT-Token.jmx
- scenario22/jmeter/05-Scenario-22-Delete-IDP.jmx
- scenario22/jmeter/06-Scenario-22-Delete-SP.jmx
- scenario22/jmeter/07-Scenario-22-Remove-Test-Users.jmx
- scenario22/jmeter/22-pre-scenario-steps.sh
- scenario22/resources/user.properties
- scenario22/teardown.sh
Update the Jmeter scripts doing necessary changes to make them Testgrid compatible
Update Base-setup.sh to deploy Playground web app 
Update Teardown.sh
Update Pre-scenario.sh
Update user.properties
Rename .jmx files
Remove hard coded values
> Modify Scenario 22 Scripts to make it Testgrid compatible

- scenario09/README.md
- scenario09/base-setup.sh
- scenario09/jmeter/01-Scenario-09-MultilayerApproval.jmx
- scenario09/jmeter/09-pre-scenario-steps.sh
- scenario09/resources/user.properties
- scenario09/teardown.sh
> Fixed the intermittent failure is loading a workflow approval request in the dashboard. 
Remove the setup configurations from base-setup.sh and teardown.sh scripts. 
Create the readme file.
> Improved the scenario to fix the intermittent failures

- scenario28/jmeter/01-Scenario-28-HomeRelam.jmx
> Remove the reference to the result file location
> remove the result file refferene

- pom.xml
> Change the version in the POM file for the 5.4.x branch
> Change the branch version to 5.4.x

- pom.xml
> Maintain the branch version as 5.5.0 Snapshot in the master branch
> Change the branch version to 5.5.0 Snapshot

- scenario28/jmeter/01-Scenario-28-HomeRelam.jmx
> Modify the scenario to comply with the GDPR - User Consent
> Modify the scenarios to comply with GDPR- User Consent

- scenario12/jmeter/01-Scenario-12-ClaimMapper.jmx
- scenario12/resources/user.properties
> Fix sol 12 to make GDPR compliant
> Fix sol 12 to make GDPR compliant

- scenario03/jmeter/01-Scenario-03-ProvisionFederatedUsersBytheIdentityProvider.jmx
> Verified and fixed sol 03 to make GDPR compliant
> Verified and Fixed sol 03 to make GDPR compliant

- scenario01/base-setup.sh
- scenario01/jmeter/01-Scenario-1-SSO-multiple-heterogeneous-IDFP.jmx
> Include the missing serverHost in basesetup.sh and redirect the request call
> Include the missing serverHost and redirect the request calls

- scenario01/base-setup.sh
> Added the missing serverHost parameter
> Added the missing serverHost parameter

- scenario03/base-setup.sh
- scenario12/base-setup.sh
- scenario12/jmeter/01-Scenario-12-ClaimMapper.jmx
- scenario12/resources/user.properties
- scenario21/base-setup.sh
Disable response signing and assertion signing in travelocity properties
> disable response signing and assertion signing properties in travelocity properties

- scenario28/resources/user.properties
> Change the twitter app credentials
> Change the twitter app credentials

- apps/PassiveSTSSampleApp/pom.xml
- apps/PassiveSTSSampleApp/src/main/webapp/WEB-INF/web.xml
- apps/playground2/pom.xml
- apps/playground2/src/main/org/wso2/sample/identity/oauth2/IDTokenDecrypterServlet.java
- apps/playground2/src/main/webapp/WEB-INF/web.xml
- apps/playground2/src/main/webapp/oauth2-authorize-user.jsp
- apps/playground2/src/main/webapp/oauth2.jsp
- apps/sso-agent-sample/pom.xml
> Update playground travelocity passivests web apps to IS550

- apps/PassiveSTSSampleApp/pom.xml
- apps/playground2/pom.xml
update playground and passive sts pom file version
> Update playground and passivests pom version to 5.5.0

- config-sets/config02/apply-config.sh
- config-sets/config02/revert-config.sh
- Modified to configure IdentityProviderSSOServiceURL and AssertionConsumerServiceURL in the authenticators.xml file
> Improve the config set 02

- scenario11/base-setup.sh
- scenario11/jmeter/01-Scenario-11-Identity-federation-between-sps-and-idps.jmx
- scenario11/resources/user.properties
> Add script modifications to sol 11
> Add script modifications to sol 11

- scenario01/jmeter/01-Scenario-1-SSO-multiple-heterogeneous-IDFP.jmx
- scenario03/jmeter/01-Scenario-03-ProvisionFederatedUsersBytheIdentityProvider.jmx
- scenario09/jmeter/01-Scenario-09-MultilayerApproval.jmx
- scenario11/jmeter/01-Scenario-11-Identity-federation-between-sps-and-idps.jmx
- scenario12/jmeter/01-Scenario-12-ClaimMapper.jmx
- scenario21/jmeter/01-Scenario-21-EnforceUsersToProvideMissingRequiredAttributesWhileGettingJITProvisioned.jmx
- scenario22/jmeter/01-Scenario-22-Create-Test-Users.jmx
- scenario22/jmeter/02-Scenario-22-Create-IDP.jmx
- scenario22/jmeter/03-Scenario-22-Create-SP.jmx
- scenario22/jmeter/04-Scenario-22-SAML2-Get-JWT-Token.jmx
- scenario22/jmeter/05-Scenario-22-Delete-IDP.jmx
- scenario22/jmeter/06-Scenario-22-Delete-SP.jmx
- scenario22/jmeter/07-Scenario-22-Remove-Test-Users.jmx
- scenario23/jmeter/01-Scenario-23-BasicAuthRequestPathAuthenticator-RegisterTravelocityApp.jmx
- scenario23/jmeter/02-Scenario-23-BasicAuthRequestPathAuthenticator-RegisterAvisApp.jmx
- scenario23/jmeter/03-Scenario-23-BasicAuthRequestPathAuthenticator-LegacyAppLogin.jmx
- scenario23/jmeter/04-Scenario-23-OAuthBearerRequestPathAuthenticator-RegisterOAuthApp.jmx
- scenario23/jmeter/05-Scenario-23-OAuthBearerRequestPathAuthenticator-Login.jmx
- scenario23/jmeter/06-Scenario-23-OAuthBearerRequestPathAuthenticator-Negative1.jmx
- scenario23/jmeter/07-Scenario-23-OAuthBearerRequestPathAuthenticator-Negative2.jmx
- scenario23/jmeter/08-Scenario-23-RemoveSps.jmx
- scenario28/jmeter/01-Scenario-28-HomeRelam.jmx
Change the name of the jtl to match with the scenario to identify the results files uniquely
> Change the name of the jtl to match with the scenario 

- scenario21/jmeter/01-Scenario-21-EnforceUsersToProvideMissingRequiredAttributesWhileGettingJITProvisioned.jmx
removed the hardcoded path for the jtl file for scenario21
> removed the hardcoded path for the jtl file for scenario21

- scenario01/run-scenario.sh
> Including pre scenario and post scenario to the run-scenario.sh file
> Scenario 01 - Adding the pre/post scenarios to run-scenario.sh

- scenario17/jmeter/17-post-scenario-steps.sh
- scenario17/jmeter/17-pre-scenario-steps.sh
updated the pre and post shell scripts to add the source command instead of .
> updated the pre and post shell scripts

- WSO2Scenariofile.yaml
- config-sets/config05/apply-config.sh
- config-sets/config05/config-init.sh
- config-sets/config05/revert-config.sh
- config-sets/config05/trial.sh
- scenario27/README.md
- scenario27/jmeter/27-pre-scenario-steps.sh
- scenario27/jmeter/Scenario-27-AttributeStoreValidations.jmx
- scenario27/resources/user.properties
- scenario27/run-scenario.sh
> The PR looks at fixing the following
1.to add a config set for applying the preconditions
2.to add a flows to add users/user roles and update user profile
3.to add a flow to submit user consent
4.to add a flow to login and view the shared attributes
> This script looks at covering the scenario27 regarding the flow where user attributes are on separate user stores to the user who is on another user store. When the user consent UI comes the user attributes of all user stores should be listed.
> Scenario27 of :https://medium.facilelogin.com/thirty-solution-patterns-with-the-wso2-identity-server-16f9fd0c0389
> Brief description of the new feature or bug fix as it will appear in the release notes
> Doc Impact :The IS documentation needs to be updated to meet the solution pattern …
> The fixes for scenario27

- config-sets/config01/apply-config.sh
- config-sets/config01/revert-config.sh
- config-sets/config02/apply-config.sh
- config-sets/config02/revert-config.sh
- config-sets/config03/apply-config.sh
- config-sets/config03/revert-config.sh
- config-sets/config04/apply-config.sh
- config-sets/config04/revert-config.sh
- config-sets/config05/apply-config.sh
- config-sets/config05/revert-config.sh
Currently config set serverHost and serverPort taken as environment variable. This will set it with default values for serverHost as localhost and default port as 9443 which are default values for the IS server. 
Here configSetHome set with pwd and we need to update this folder with all required files such as org.soasecurity.user.mgt.attribute.store.extension-1.0.0.jar, mysqlJAR and oauth2-proxy.war since script using these files.
> set serverHost/serverPort with default value

- integration-tests/README.md
- integration-tests/configure_product.py
- integration-tests/const.py
- integration-tests/requirements.txt
- integration-tests/run-intg-test.py
Create directory to maintain integration test automation scripts
Implement and maintain automation scripts for running product integration tests on TestGrid
> add integration-tests repo

- integration-tests/configure_product.py
- integration-tests/const.py
- integration-tests/intg-test-runner.bat
- integration-tests/intg-test-runner.sh
- integration-tests/run-intg-test.py
- integration-tests/run-scenario.sh
To add integration test automation scripts which will create the necessary environment for the product, configure the product as per the situation, run integration tests on it and finally fetch the test-results from the build.
Automate configuring product accordingly and running integration tests on it.
- Ran FindSecurityBugs plugin and verified report? yes
> Adding integration test automation resources for IS.

- integration-tests/configure_product.py
- integration-tests/const.py
Resolves:#311 
Visualize JVM metrics in Dashboard
Attach Jolokia java agent which will pull JVM metrics from the JVM of the tested product. 
- Ran FindSecurityBugs plugin and verified report? yes
> Attach jolokia agent to product-is at runtime 

- integration-tests/run-intg-test.py
**Improvements done:**
1. Improve the python script to source the Identity dbscript in to carbon DB
* Modify the setup database method.
2. Improve the script to print some logs when running the each database.
> improve the script to source the identity DB script and adding some logs.

- integration-tests/run-scenario.sh
**Purpose**
Add Red Hat Linux 7.4 to testgrid
**Goals**
Run tests in RHEL
**Approach**
Created an AMI for RHEL and added a new OS infra parameter to testgriddb. Finally modified the CF script and run-scenario.sh 
**Security checks**
- Ran FindSecurityBugs plugin and verified report? yes
> Add RHEL to run-scenario.sh

- integration-tests/run-intg-test.py
> Update run-intg-test.py 

- integration-tests/run-scenario.sh
The PR contains necessary changes to align the integration tests with the latest TestGrid-expected-standards.
- Ran FindSecurityBugs plugin and verified report? yes
> Modify structure of integration tests to align with current TestGrid execution

- integration-tests/prod_test_constant.py
> Add UMA and Consent scripts

- integration-tests/run-integration.sh
- integration-tests/run-intg-test.py
Resolves https://github.com/wso2/identity-test-integration/issues/334
Add run-integration.sh 
- Ran FindSecurityBugs plugin and verified report? N/A
CentOS 7
> Add run-integration.sh

- integration-tests/run-integration.sh
Fix path errors with Ubuntu
Run integration tests
- Ran FindSecurityBugs plugin and verified report? N/A
Ubuntu 18.04
CentOS 7.5
JDK 11
> Fix errors with Ubuntu

- integration-tests/test.sh
Change to The branch corresponding to new config model in this repo https://github.com/wso2-incubator/test-integration-tests-runner.git
> Change incubator branch for new config model
